USE [Dc2]
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pass' AND COLUMN_NAME = 'IVM_PERMISSIONS')
	ALTER TABLE Dc2..pass ADD IVM_PERMISSIONS NVARCHAR(MAX);
GO

IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'pass' AND COLUMN_NAME = 'IVMD_PERMISSIONS')
	ALTER TABLE Dc2..pass ADD IVMD_PERMISSIONS NVARCHAR(MAX);
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[IVAN_WEB_MENU]') AND type in (N'U'))
	DROP TABLE [dbo].[IVAN_WEB_MENU_DETAIL]
GO

CREATE TABLE [dbo].[IVAN_WEB_MENU](
	[IVM_SEQ] [bigint] NOT NULL,
	[IVM_TITLE] [nvarchar](40) NULL,
	[IVM_PROG_NAME] [nvarchar](40) NULL,
	[IVM_PARENT_SEQ] [bigint] NULL,
	[IVM_RANK] [int] NULL,
	[IVM_REMARK] [nvarchar](max) NULL,
	[CREATE_USER] [varchar](20) NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](20) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_IVAN_WEB_MENU] PRIMARY KEY CLUSTERED 
(
	[IVM_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

-------------------------------------[IVAN_WEB_MENU_DETAIL]
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[IVAN_WEB_MENU_DETAIL]') AND type in (N'U'))
	DROP TABLE [dbo].[IVAN_WEB_MENU_DETAIL]
GO

CREATE TABLE [dbo].[IVAN_WEB_MENU_DETAIL](
	[IVMD_SEQ] [bigint] NOT NULL,
	[IVM_SEQ] [bigint] NOT NULL,
	[IVMD_ELEMENT_TITLE] [nvarchar](40) NULL,
	[IVMD_CHECK] [bit] NULL,
	[IVMD_REMARK] [nvarchar](max) NULL,
	[CREATE_USER] [varchar](20) NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_USER] [varchar](20) NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_IVAN_WEB_MENU_DETAIL] PRIMARY KEY CLUSTERED 
(
	[IVMD_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO