DROP FUNCTION IF EXISTS [dbo].[FN_GET_NUM2WORD]
GO

CREATE FUNCTION [dbo].[FN_GET_NUM2WORD] (
  @M_AMOUNT AS NUMERIC(18,2)
) RETURNS VARCHAR(MAX)
BEGIN
  DECLARE @M_RS AS NUMERIC(18,0)
  DECLARE @M_PAISA AS NUMERIC(18,0)
  DECLARE @M_CURRENT AS NUMERIC(18,0)
  DECLARE @M_RETSTR AS VARCHAR(MAX)
  DECLARE @M_POSTFIX AS VARCHAR(20)    
  DECLARE @M_DIGIWORD AS VARCHAR(100)
  SET @M_AMOUNT = ISNULL(@M_AMOUNT,0)
  SET @M_RS = LEFT(@M_AMOUNT,LEN(@M_AMOUNT)-3)
  SET @M_PAISA = RIGHT(@M_AMOUNT,2)
  SET @M_RETSTR = ''
  IF @M_RS = 0 AND @M_PAISA = 0 
  BEGIN
    SET @M_RETSTR = ''
  END
  ELSE
  BEGIN
    IF @M_RS = 0
    BEGIN
      SET @M_RETSTR = ''
    END
    ELSE
    BEGIN
      WHILE @M_RS > 0
      BEGIN
        SELECT @M_CURRENT = 
          CASE WHEN LEN(@M_RS) = 3 OR LEN(@M_RS) = 7 THEN LEFT(@M_RS,1)
			   WHEN LEN(@M_RS) <= 2 THEN LEFT(@M_RS,2)
			   ELSE CASE WHEN (LEN(@M_RS)-2) % 2 = 0 THEN LEFT(@M_RS,1) ELSE LEFT(@M_RS,2) END
			   END
        
        SELECT @M_DIGIWORD = [dbo].[FN_GET_DIGIT2WORD](@M_CURRENT)
        SELECT @M_POSTFIX = CASE 
        WHEN LEN(@M_RS) = 7 OR LEN(@M_RS) = 8 THEN 'MILLION' 
		WHEN LEN(@M_RS) = 6 THEN 'HUNDRED'
        WHEN LEN(@M_RS) = 4 OR LEN(@M_RS) = 5 THEN 'THOUSAND'  
        WHEN LEN(@M_RS) = 3 THEN 'HUNDRED'
        ELSE '' END
        
        SELECT @M_RS = CASE WHEN LEN(@M_RS) > 2 THEN RIGHT(@M_RS,LEN(@M_RS)-LEN(@M_CURRENT)) ELSE 0 END
        SET @M_RETSTR = @M_RETSTR + ' ' + @M_DIGIWORD + ' ' + @M_POSTFIX
      END
    END
    IF @M_PAISA = 0 
    BEGIN
      SET @M_RETSTR = @M_RETSTR
    END
    ELSE IF LEN(@M_RETSTR) != 0 
    BEGIN
      SELECT @M_DIGIWORD = [dbo].[FN_GET_DIGIT2WORD](@M_PAISA)
      SET @M_RETSTR = @M_RETSTR + 'AND CENTS ' + @M_DIGIWORD
    END
	ELSE
	BEGIN
		SELECT @M_DIGIWORD = [dbo].[FN_GET_DIGIT2WORD](@M_PAISA)
		SET @M_RETSTR = 'CENTS ' + @M_DIGIWORD
	END
  END
    
  RETURN RTRIM(LTRIM(@M_RETSTR))
END